sroSite/Controllers/sroProposalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sroSite.Models;

namespace sroSite.Controllers
{
    [Authorize]
    public class sroProposalsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();        

        // GET: sroProposals
        public async Task<ActionResult> Index()
        {
            int page = 1;
            string search = Request["search"];
            int searchchanged = 0;
            IQueryable<sroProposal> result = db.sroProposals.Include(s => s.Call);

            if (User.IsInRole("sroAgent"))
            {
                result = db.sroAgents.Where(a => a.UId == User.Identity.Name).SelectMany(x => x.Sites).SelectMany(s => s.CallsTechSites).Select(c => c.Call).SelectMany(t => t.Proposals).Distinct();
            }
            if (User.IsInRole("sroNegotiator"))
            {
                result = db.sroNegotiators.Where(n => n.UId == User.Identity.Name).SelectMany(x => x.Sites).SelectMany(s => s.CallsTechSites).Select(c => c.Call).SelectMany(t => t.Proposals).Distinct();                
            }

            if (!String.IsNullOrEmpty(Request["page"]) && int.TryParse(Request["page"], out page))
            {

            }
            else
            {
                page = 1;
            }

            if (!String.IsNullOrEmpty(Request["searchchanged"]) && Request["searchchanged"] == "1")
            {
                page = 1;
            }

            if (!string.IsNullOrEmpty(search))
            {
                result = result.Where(x => x.Call.CallsTechSites.FirstOrDefault().TechSite.Contact.Landlord.Name.Contains(search));
            }

            if (result != null)
            {
                ViewBag.TotalCount = result.Count();
            }
            else
            {
                ViewBag.TotalCount = 0;
            }

            result = result.OrderByDescending(x => x.Id).Skip(12 * (page - 1)).Take(12);

            ViewBag.page = page;
            return View(await result.ToListAsync());
        }

        // GET: sroProposals/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroProposal sroProposal = await db.sroProposals.FindAsync(id);
            if (sroProposal == null)
            {
                return HttpNotFound();
            }
            return View(sroProposal);
        }

        // GET: sroProposals/Create
        public ActionResult Create(int? callId)
        {
            //ViewBag.CallId = new SelectList(db.sroCalls, "Id", "Status");

            if (!callId.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var call = db.sroCalls.Where(x => x.Id == callId).SingleOrDefault();
            if (call == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            ViewBag.CallId = call.Id;

            return View();
        }

        // POST: sroProposals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,DecreaseValue,DecreasePercent,DecreaseStart,DecreaseEnd,Prepayment,HasAdditionalCosts,IsLandlordProposal,Success,CallId")] sroProposal sroProposal)
        {
            if (ModelState.IsValid)
            {
                db.sroProposals.Add(sroProposal);
                await db.SaveChangesAsync();
                return RedirectToAction("Edit", "sroCalls", new { Id = sroProposal.CallId });
            }

            ViewBag.CallId = sroProposal.CallId;
            //ViewBag.CallId = new SelectList(db.sroCalls, "Id", "Id", sroProposal.CallId);
            return View(sroProposal);
        }

        // GET: sroProposals/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroProposal sroProposal = await db.sroProposals.FindAsync(id);
            if (sroProposal == null)
            {
                return HttpNotFound();
            }
            ViewBag.CallId = new SelectList(db.sroCalls, "Id", "Status", sroProposal.CallId);
            return View(sroProposal);
        }

        // POST: sroProposals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,DecreaseValue,DecreasePercent,DecreaseStart,DecreaseEnd,Prepayment,HasAdditionalCosts,IsLandlordProposal,Success,CallId")] sroProposal sroProposal)
        {
            var currProposal = db.sroProposals.Where(x => x.Id == sroProposal.Id).FirstOrDefault();

            currProposal.DecreaseValue = sroProposal.DecreaseValue;
            currProposal.DecreasePercent = sroProposal.DecreasePercent;
            currProposal.DecreaseStart = sroProposal.DecreaseStart;
            currProposal.DecreaseEnd = sroProposal.DecreaseEnd;
            currProposal.Prepayment = sroProposal.Prepayment;
            currProposal.HasAdditionalCosts = sroProposal.HasAdditionalCosts;
            currProposal.IsLandlordProposal = sroProposal.IsLandlordProposal;
            currProposal.Success = sroProposal.Success;

            if (ModelState.IsValid)
            {
                db.Entry(currProposal).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CallId = new SelectList(db.sroCalls, "Id", "Status", sroProposal.CallId);
            return View(sroProposal);
        }

        // GET: sroProposals/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroProposal sroProposal = await db.sroProposals.FindAsync(id);
            if (sroProposal == null)
            {
                return HttpNotFound();
            }
            return View(sroProposal);
        }

        // POST: sroProposals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            sroProposal sroProposal = await db.sroProposals.FindAsync(id);
            db.sroProposals.Remove(sroProposal);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sroSite/Views/sroProposals/Create.cshtml
@model sroSite.Models.sroProposal

@{
    ViewBag.Title = "Предложения";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="panel panel-default" style="margin-top: 15px;">
        <div class="panel-heading"><h4>Добавить предложение к звонку <strong>@ViewBag.CallId</strong></h4></div>
        <div class="panel-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @{
                Html.EnableClientValidation(false);
            }

            <div class="well">
                @{              
                    int CallId = -1;
                    if (ViewBag.CallId != null)
                    {
                        int.TryParse(ViewBag.CallId.ToString(), out CallId);
                    }
                    sroSite.Models.ApplicationDbContext db = sroSite.Models.ApplicationDbContext.Create();
                    var Call = db.sroCalls.Where(x => x.Id == CallId).FirstOrDefault();
                    var Contact = db.sroLandlordContacts.Where(x => x.Id == Call.ContactId).FirstOrDefault();
                    var Landlord = Contact != null ? Contact.Landlord : null;
                    var TechSites = db.sroCalls.Where(c => c.Id == CallId).SelectMany(t => t.CallsTechSites).Select(s => s.TechSite);
                }
                @if (CallId > -1)
                {
                    decimal? totalPrice = 0;
                    foreach (var site in TechSites)
                    {
                        totalPrice += site.PricePerMonth != null ? site.PricePerMonth : 0;
                    }
                    <span>Сайтов:&nbsp;@(TechSites.Count().ToString())&nbsp;на&nbsp;сумму&nbsp;@(totalPrice.ToString())&nbsp;руб.</span>
                }
                else
                {
                    <span class="warning">Звонок не найден</span>
                }
            </div>
            
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.DecreaseValue, "Снижение, руб. в мес. без НДС", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DecreaseValue, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DecreaseValue, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DecreasePercent, "Снижение, %", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DecreasePercent, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DecreasePercent, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DecreaseStart, "Дата начала", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DecreaseStart, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DecreaseStart, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DecreaseEnd, "Дата окончания", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DecreaseEnd, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DecreaseEnd, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Prepayment, "Аванс, мес.", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Prepayment, new { htmlAttributes = new { @class = "form-control", @id = "Prepayment" } })
                        @Html.ValidationMessageFor(model => model.Prepayment, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.HasAdditionalCosts, "Доп. затраты", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => model.HasAdditionalCosts)
                            @Html.ValidationMessageFor(model => model.HasAdditionalCosts, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsLandlordProposal, "Предложение контрагента", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => model.IsLandlordProposal)
                            @Html.ValidationMessageFor(model => model.IsLandlordProposal, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <hr />

                <div class="form-group">
                    @Html.LabelFor(model => model.Success, "Принято", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Success)
                            @Html.ValidationMessageFor(model => model.Success, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
       

             

        <div class="form-group">            
            <input type="submit" value="Добавить" class="btn btn-default" onclick="SetDefaultValues()" style="margin-left: 0px;"/>
        </div>
}

<div>
    @Html.ActionLink("К списку предложений", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function SetDefaultValues()
        {
            var currVal = document.getElementById("Prepayment").value;
            if (currVal == "")
            {
                document.getElementById("Prepayment").setAttribute("value", "0");
            }
        }
    </script>
}

sroSite/Views/sroProposals/Delete.cshtml
@model sroSite.Models.sroProposal

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>sroProposal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Call.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Call.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DecreaseValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DecreaseValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DecreasePercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DecreasePercent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DecreaseStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DecreaseStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DecreaseEnd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DecreaseEnd)
        </dd>        

        <dt>
            @Html.DisplayNameFor(model => model.Prepayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prepayment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HasAdditionalCosts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HasAdditionalCosts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsLandlordProposal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsLandlordProposal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Success)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Success)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

sroSite/Views/sroProposals/Details.cshtml
@model sroSite.Models.sroProposal

@{
    ViewBag.Title = "Предложения";
}

<h2>Предложения</h2>

<div>
    <h4>@Model.Id</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <span>Звонок</span>
        </dt>

        <dd>
            <a href="@Url.Action("Details", "sroCalls", new { Id = Model.CallId })">
                @Html.DisplayFor(model => model.Call.Id)
            </a>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DecreaseValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DecreaseValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DecreasePercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DecreasePercent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DecreaseStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DecreaseStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DecreaseEnd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DecreaseEnd)
        </dd>                

        <dt>
            @Html.DisplayNameFor(model => model.Prepayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prepayment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HasAdditionalCosts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HasAdditionalCosts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsLandlordProposal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsLandlordProposal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Success)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Success)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

sroSite/Views/sroProposals/Edit.cshtml
@model sroSite.Models.sroProposal

@{
    ViewBag.Title = "Предложения";
}

<h2>Предложение&nbsp;@Model.Id</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @{
            Html.EnableClientValidation(false);
        }

        <div class="form-group">
            @Html.LabelFor(model => model.CallId, "CallId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label name="CallId" id="CallId" for="CallId" class="form-control text-box single-line" type="text" style="width: 280px;">
                    @Model.CallId
                </label>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.DecreaseValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DecreaseValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DecreaseValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DecreasePercent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DecreasePercent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DecreasePercent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DecreaseStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DecreaseStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DecreaseStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DecreaseEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DecreaseEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DecreaseEnd, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            @Html.LabelFor(model => model.Prepayment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prepayment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prepayment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HasAdditionalCosts, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.HasAdditionalCosts)
                    @Html.ValidationMessageFor(model => model.HasAdditionalCosts, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsLandlordProposal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsLandlordProposal)
                    @Html.ValidationMessageFor(model => model.IsLandlordProposal, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Success, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Success)
                    @Html.ValidationMessageFor(model => model.Success, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К списку предложений", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sroSite/Views/sroProposals/Index.cshtml
@model IEnumerable<sroSite.Models.sroProposal>

@{
    ViewBag.Title = "Предложения";
}

<h2>Предложения</h2>

@{
    int page;
    string search;
}
@if (Request["page"].IsInt())
{
    if (int.TryParse(Request["page"], out page))
    {

    }
    else
    {
        page = 1;
    }
}
else
{
    page = 1;
}
@if (ViewBag.page > 0)
{
    page = ViewBag.page;
}
@if (!Request["search"].IsEmpty())
{
    search = Request["search"];
}
else
{
    search = string.Empty;
}

<form id="navData" name="navData">
    <div class="row">
        <div class="col-md-9">
            @if (ViewBag.TotalCount > 12)
            {
                <ul class="pagination" style="margin-top: 0px; margin-bottom: 5px;">
                    @for (int i = 0; i < ViewBag.TotalCount; i += 12)
                    {
                        <li class="@(page == ((i / 12) + 1) ? "active" : "")"><a href="@(Url.Action("Index", new { page = ((i / 12) + 1), search = search }))">@((i / 12) + 1)</a></li>
                    }
                </ul>
            }
        </div>
        <div class="col-md-3">
            <div class="input-group" style="margin-top: 0px; margin-bottom: 10px;">
                <!--<div class="form-group has-feedback has-clear">-->
                <input type="text" class="form-control" placeholder="Поиск" value="@(String.IsNullOrEmpty(search) ? "" : search)" onkeyup="searchKeyUp()" id="searchfield">
                <!--<span class="form-control-clear glyphicon glyphicon-remove form-control-feedback hidden" style="z-index: 10;pointer-events: auto;cursor: pointer;"></span>-->
                <!--</div>-->
                <div class="input-group-btn">
                    <button class="btn btn-default" style="height:34px;" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    @Html.Hidden("page", page)
    @Html.Hidden("search", search)
    @Html.Hidden("searchchanged")
</form>



<table class="table">
    <tr>
        <th>
            <span>Id</span>
        </th>
        <th>
            <span>Звонок</span>
        </th>
        <th>
            <span>Контрагент</span>
        </th>
        <th>
            <span>Снижение, руб. в мес.</span>
        </th>
        <th>
            <span>Снижение, %</span>
        </th>
        <th>
            <span>Дата</span>
        </th>       
        <th>
            <span>Аванс</span>
        </th>
        <th>
            <span>Статус</span>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Call.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Call.CallsTechSites.FirstOrDefault().TechSite.Contact.Landlord.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DecreaseValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DecreasePercent)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DecreaseStart)
        </td>       
        <td>
            @Html.DisplayFor(modelItem => item.Prepayment)
        </td>
        <td>
            @{
                string state = "Рассматривается";
                if (item.Success.HasValue && item.Success == true)
                {
                    state = "Принято";
                }
                if (item.Success.HasValue && item.Success == false)
                {
                    state = "Отклонено";
                }
            }
            <span>@state</span>
        </td>
        <td style="vertical-align: middle; text-align: center; min-width: 90px;">
            <a href="@Url.Action("Edit", "sroProposals", new { id = item.Id })"><span class="glyphicon glyphicon-pencil"></span></a>
            <a href="@Url.Action("Details", "sroProposals", new { id = item.Id })"><span class="glyphicon glyphicon-list-alt"></span></a>
            <a href="@Url.Action("Delete", "sroProposals", new { id = item.Id })"><span class="glyphicon glyphicon-trash"></span></a>
        </td>
    </tr>
}

</table>
@section Scripts {
    <script>
        function searchKeyUp() {
            document.getElementById("search").value = document.getElementById("searchfield").value;
            document.getElementById("searchchanged").value = 1;
        }

        $('.has-clear input[type="text"]').on('input propertychange', function () {
            var $this = $(this);
            var visible = Boolean($this.val());
            $this.siblings('.form-control-clear').toggleClass('hidden', !visible);
        }).trigger('propertychange');

        $('.form-control-clear').click(function () {
            $(this).siblings('input[type="text"]').val('')
                .trigger('propertychange').focus();
        });
    </script>
}