sroSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sroSite.Models;

namespace sroSite.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var dbc = sroSite.Models.ApplicationDbContext.Create();


            List<int> siteStates = new List<int>();
            decimal savings = 0;
            for (int i = 0; i < 11; i++)
            {
                siteStates.Add(0);
            }
            List<sroTechSite> sites = dbc.sroTechSites.ToList();
            foreach (var site in sites)
            {
                switch (site.Status)
                {
                    case "Новый": siteStates[0] += 1; break;
                    case "Подготовка": siteStates[1] += 1; siteStates[3] += 1; break;
                    case "Дозвон": siteStates[1] += 1; siteStates[4] += 1; break;
                    case "Рассмотрение": siteStates[1] += 1; siteStates[5] += 1; break;
                    case "Реализация": siteStates[1] += 1; siteStates[6] += 1; break;
                    case "Снижение": siteStates[2] += 1; siteStates[7] += 1; break;
                    case "Удержание": siteStates[2] += 1; siteStates[8] += 1; break;
                    case "Рост": siteStates[2] += 1; siteStates[9] += 1; break;
                    case "Недозвон": siteStates[2] += 1; siteStates[10] += 1; break;
                    default: siteStates[0] += 1; break;
                }
                if (site.EffectRep != null && site.EffectRep.HasValue && site.EffectRep < 0)
                {
                    savings += site.EffectRep.Value;
                }
            }

            ViewBag.SiteStates = siteStates;
            ViewBag.Savings = savings;

            List<sroSite.Models.sroAgent> agents = dbc.sroAgents.ToList();

            List<int> sitesCount = new List<int>();
            List<int> finishedSitesCount = new List<int>();
            List<int> callsCount = new List<int>();

            foreach(var item in agents)
            { 
                var sroTechSitesAgent = db.sroTechSites.Include(s => s.Agent).Include(s => s.Contact.Landlord).Include(s => s.Contact).Include(s => s.Negotiator).Where(s => s.Agent.UId == item.UId);
                var sroTechSitesFinishedAgent = db.sroTechSites.Include(s => s.Agent).Include(s => s.Contact.Landlord).Include(s => s.Contact).Include(s => s.Negotiator).Where(s => s.Agent.UId == item.UId && (s.Status == "Снижение" || s.Status == "Удержание" || s.Status == "Рост" || s.Status == "Недозвон"));
                var agentCalls = db.sroAgents.Where(a => a.UId == item.UId).SelectMany(x => x.Sites).SelectMany(s => s.CallsTechSites).Select(c => c.Call).Distinct();
                sitesCount.Add(sroTechSitesAgent.Count());
                finishedSitesCount.Add(sroTechSitesFinishedAgent.Count());
                callsCount.Add(agentCalls.Count());
            }

            ViewBag.Agents = agents;
            ViewBag.SitesCount = sitesCount;
            ViewBag.FinishedSitesCount = finishedSitesCount;
            ViewBag.CallsCount = callsCount;

            ViewBag.AgentSitesCount = db.sroTechSites.Include(s => s.Agent).Include(s => s.Contact.Landlord).Include(s => s.Contact).Include(s => s.Negotiator).Where(s => s.Agent.UId == User.Identity.Name).Count();
            ViewBag.AgentCallsCount = db.sroAgents.Where(a => a.UId == User.Identity.Name).SelectMany(x => x.Sites).SelectMany(s => s.CallsTechSites).Select(c => c.Call).Distinct().Count();
            ViewBag.AgentTasksCount = db.sroAgents.Where(a => a.UId == User.Identity.Name).SelectMany(x => x.Sites).SelectMany(s => s.CallsTechSites).Select(c => c.Call).SelectMany(t => t.Tasks).Distinct().Count();

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

sroSite/Controllers/sroAgentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sroSite.Models;

namespace sroSite.Controllers
{
    [Authorize]
    public class sroAgentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: sroAgents
        public async Task<ActionResult> Index()
        {
            return View(await db.sroAgents.ToListAsync());
        }

        // GET: sroAgents/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroAgent sroAgent = await db.sroAgents.FindAsync(id);
            if (sroAgent == null)
            {
                return HttpNotFound();
            }
            return View(sroAgent);
        }

        // GET: sroAgents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: sroAgents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,UId,Name,FIO,Phone")] sroAgent sroAgent)
        {
            if (ModelState.IsValid)
            {
                db.sroAgents.Add(sroAgent);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(sroAgent);
        }

        // GET: sroAgents/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroAgent sroAgent = await db.sroAgents.FindAsync(id);
            if (sroAgent == null)
            {
                return HttpNotFound();
            }
            return View(sroAgent);
        }

        // POST: sroAgents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,UId,Name,FIO,Phone")] sroAgent sroAgent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sroAgent).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(sroAgent);
        }

        // GET: sroAgents/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroAgent sroAgent = await db.sroAgents.FindAsync(id);
            if (sroAgent == null)
            {
                return HttpNotFound();
            }
            return View(sroAgent);
        }

        // POST: sroAgents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            sroAgent sroAgent = await db.sroAgents.FindAsync(id);
            db.sroAgents.Remove(sroAgent);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sroSite/Controllers/sroTasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sroSite.Models;

namespace sroSite.Controllers
{
    [Authorize]
    public class sroTasksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: sroTasks
        public async Task<ActionResult> Index()
        {
            int page = 1;
            string search = Request["search"];
            int searchchanged = 0;
            IQueryable<sroTask> result = db.sroTasks.Include(s => s.Call);

            if (User.IsInRole("sroManager"))
            {
                result = db.sroTasks.Include(s => s.Call);
            }
            if (User.IsInRole("sroAgent"))
            {
                result = db.sroAgents.Where(a => a.UId == User.Identity.Name).SelectMany(x => x.Sites).SelectMany(s => s.CallsTechSites).Select(c => c.Call).SelectMany(t => t.Tasks).Distinct();
            }
            if (User.IsInRole("sroNegotiator"))
            {
                var sroTasksNegotiator = db.sroNegotiators.Where(n => n.UId == User.Identity.Name).SelectMany(x => x.Sites).SelectMany(s => s.CallsTechSites).Select(c => c.Call).SelectMany(t => t.Tasks).Distinct().ToList();
                var sroTasksResponsible = db.sroNegotiators.SelectMany(x => x.Sites).SelectMany(s => s.CallsTechSites).Select(c => c.Call).SelectMany(t => t.Tasks).Where(t => t.Responsible == User.Identity.Name).Distinct().ToList();
                foreach (sroTask respTask in sroTasksResponsible)
                {
                    if (sroTasksNegotiator.IndexOf(respTask) == -1)
                    {
                        sroTasksNegotiator.Add(respTask);
                    }
                }
                result = sroTasksNegotiator.AsQueryable();
            }

            if (!String.IsNullOrEmpty(Request["page"]) && int.TryParse(Request["page"], out page))
            {

            }
            else
            {
                page = 1;
            }

            if (!String.IsNullOrEmpty(Request["searchchanged"]) && Request["searchchanged"] == "1")
            {
                page = 1;
            }

           

            if (!string.IsNullOrEmpty(search))
            {
                result = result.Where(x => x.Call.CallsTechSites.FirstOrDefault().TechSite.Contact.Landlord.Name.Contains(search));
            }

            if (result != null)
            {
                ViewBag.TotalCount = result.Count();
            }
            else
            {
                ViewBag.TotalCount = 0;
            }

            result = result.OrderByDescending(x => x.Id).Skip(12 * (page - 1)).Take(12);

            ViewBag.page = page;
            return View(await result.ToListAsync());
        }

        // GET: sroTasks/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroTask sroTask = await db.sroTasks.FindAsync(id);
            if (sroTask == null)
            {
                return HttpNotFound();
            }
            return View(sroTask);
        }

        // GET: sroTasks/Create
        public ActionResult Create(int? callId)
        {
            if (!callId.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var call = db.sroCalls.Where(x => x.Id == callId).SingleOrDefault();
            if (call == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            ViewBag.CallId = call.Id;
            return View();
        }

        // POST: sroTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Type,Status,Responsible,StartDate,LastChangeDate,EndDate,TaskData,ResponseData,EcmLink,Success,CallId")] sroTask sroTask)
        {
            if (ModelState.IsValid)
            {
                sroTask.Status = "Новая";
                sroTask.StartDate = DateTime.Now;
                sroTask.LastChangeDate = sroTask.StartDate;
                db.sroTasks.Add(sroTask);
                await db.SaveChangesAsync();
                return RedirectToAction("Edit","sroCalls",new { Id = sroTask.CallId});
            }

            ViewBag.CallId = new SelectList(db.sroCalls, "Id", "Id", sroTask.CallId);
            return View(sroTask);
        }

        // GET: sroTasks/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (User.IsInRole("sroAgent"))
            {
                Response.Redirect(Url.Action("Index"));
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroTask sroTask = await db.sroTasks.FindAsync(id);
            if (sroTask == null)
            {
                return HttpNotFound();
            }
            if (sroTask.Status == "Завершена")
            {
                return RedirectToAction("Details", new { Id = sroTask.Id });
            }
            ViewBag.CallId = new SelectList(db.sroCalls, "Id", "Id", sroTask.CallId);
            ViewBag.Negotiators = new SelectList(db.sroNegotiators, "UId", "FIO", sroTask.Responsible);
            return View(sroTask);
        }

        // POST: sroTasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Type,Status,Responsible,StartDate,LastChangeDate,EndDate,TaskData,ResponseData,EcmLink,Success,CallId")] sroTask sroTask)
        {
            var CurrTask = db.sroTasks.Where(x => x.Id == sroTask.Id).FirstOrDefault();

            bool? taskCompleteState = null;

            if(!string.IsNullOrEmpty(Request["Complete"]))
            {
                if (Request["Complete"] == "success")
                {
                    taskCompleteState = true;
                }
                if (Request["Complete"] == "negative")
                {
                    taskCompleteState = false;
                }
            }

            //sroTask.CallId = CurrTask.CallId;
            //sroTask.Type = CurrTask.Type;
            //sroTask.StartDate = CurrTask.StartDate;
            //sroTask.TaskData = CurrTask.TaskData;

            CurrTask.LastChangeDate = (sroTask.Status == CurrTask.Status) ? CurrTask.LastChangeDate : DateTime.Now;
            CurrTask.Status = sroTask.Status;
            CurrTask.Responsible = (String.IsNullOrEmpty(sroTask.Responsible)) ? null : sroTask.Responsible;
            CurrTask.ResponseData = sroTask.ResponseData;
            CurrTask.Success = taskCompleteState;

            if(sroTask.EcmLink != null)
            {
                CurrTask.EcmLink = sroTask.EcmLink;
            }

            if (CurrTask.Success != null)
            {
                CurrTask.Status = "Завершена";
                CurrTask.EndDate = DateTime.Now;
            }
            //only if not finished and not contract
            //sroTask.EcmLink = CurrTask.EcmLink;

            if (ModelState.IsValid)
            {
                db.Entry(CurrTask).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CallId = new SelectList(db.sroCalls, "Id", "Id", sroTask.CallId);
            return View(sroTask);
        }

        // GET: sroTasks/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroTask sroTask = await db.sroTasks.FindAsync(id);
            if (sroTask == null)
            {
                return HttpNotFound();
            }
            return View(sroTask);
        }

        // POST: sroTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            sroTask sroTask = await db.sroTasks.FindAsync(id);
            db.sroTasks.Remove(sroTask);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sroSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

sroSite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

sroSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "HOME";
}

@if (User.IsInRole("sroManager"))
{
    {
        List<int> siteStates = ViewBag.SiteStates;
        decimal savings = ViewBag.Savings * (-1);

    <div class="jumbotron" style="margin-bottom: 15px; margin-top: 30px;">
        <h1>Экономия: @(savings.ToString()) руб.</h1>
        <br />
        <p>
            <b>Новые сайты: @(siteStates[0].ToString())</b>
        </p>
        <p>
            <b>В работе: @(siteStates[1].ToString())</b>&nbsp;(Подготовка:&nbsp;@(siteStates[3].ToString()),&nbsp;Дозвон:&nbsp;@(siteStates[4].ToString()),&nbsp;Рассмотрение:&nbsp;@(siteStates[5].ToString()),&nbsp;Реализация:&nbsp;@(siteStates[6].ToString()))
        </p>
        <p>
            <b>Завершено: @(siteStates[2].ToString())</b>&nbsp;(Снижение:&nbsp;@(siteStates[7].ToString()),&nbsp;Удержание:&nbsp;@(siteStates[8].ToString()),&nbsp;Рост:&nbsp;@(siteStates[9].ToString()),&nbsp;Недозвон:&nbsp;@(siteStates[10].ToString()))
        </p>

        

    </div>
    }

    {
        List<sroSite.Models.sroAgent> agents = ViewBag.Agents;
        List<int> sitesCount = ViewBag.SitesCount;
        List<int> finishedSitesCount = ViewBag.FinishedSitesCount;
        List<int> callsCount = ViewBag.CallsCount;
        int currAgent = 0;

        foreach (var item in agents)
        {
            var complete = sitesCount[currAgent] != 0 ? finishedSitesCount[currAgent] * 100 / sitesCount[currAgent] : 0;

            if (currAgent % 2 == 0)
            {
                @:<div class="row" style="height: 200px;">
            }
                <div class="col-md-6" style="display: block; max-width: 555px; margin: 15px; border-radius: 6px; background-color: #eeeeee;">
                    <div>
                        <span style="font-size: 48px;">
                            @(string.IsNullOrEmpty(item.Name) ? item.FIO : item.Name )
                        </span>
                        <span style="font-size: 16px;">&nbsp;-&nbsp;Сайтов:</span>
                        <span style="font-size: 24px;">@sitesCount[currAgent]&nbsp;(@finishedSitesCount[currAgent])</span>
                        &nbsp;                        
                        <span style="font-size: 16px;">Звонков:</span>
                        <span style="font-size: 24px;">@callsCount[currAgent]</span>
                    </div>
                    <span style="font-size: 64px; padding: 0px; margin: 0px;">@complete<span>%</span></span> 
                    <p><a class="btn btn-default" href="@Url.Action("Details", "sroAgents", new { item.Id })">Просмотр &raquo;</a></p>
                </div>

            if (currAgent % 2 != 0 || currAgent == (agents.Count - 1))
            {
                @:</div>
            }
            currAgent++;
        }
    }
}

@if (User.IsInRole("sroAgent"))
{
    <div style="margin-top: 15px;"></div>
    <h2>Привет,&nbsp;@(sroSite.Models.Extensions.IdentityExtentions.GetSroUserName())!</h2>
    <div style="margin-top: 15px;"></div>
    <div class="panel panel-default">
        <div class="panel-heading">Мои сайты</div>
        <div class="panel-body">
            <h1><a href="@Url.Action("Index", "sroTechSites")">Сайты</a>&nbsp;<span class="label label-default">@(ViewBag.AgentSitesCount != null ? ViewBag.AgentSitesCount : 0)</span></h1>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Мои звонки</div>
        <div class="panel-body">
            <h1><a href="@Url.Action("Index", "sroCalls")">Звонки</a>&nbsp;<span class="label label-default">@(ViewBag.AgentCallsCount != null ? ViewBag.AgentCallsCount : 0)</span></h1>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Мои задачи</div>
        <div class="panel-body">
            <h1><a href="@Url.Action("Index", "sroTasks")">Задачи</a>&nbsp;<span class="label label-default">@(ViewBag.AgentTasksCount != null ? ViewBag.AgentTasksCount : 0)</span></h1>
        </div>
    </div>
}