sroSite/Controllers/sroAgentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sroSite.Models;

namespace sroSite.Controllers
{
    [Authorize]
    public class sroAgentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: sroAgents
        public async Task<ActionResult> Index()
        {
            return View(await db.sroAgents.ToListAsync());
        }

        // GET: sroAgents/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroAgent sroAgent = await db.sroAgents.FindAsync(id);
            if (sroAgent == null)
            {
                return HttpNotFound();
            }
            return View(sroAgent);
        }

        // GET: sroAgents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: sroAgents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,UId,Name,FIO,Phone")] sroAgent sroAgent)
        {
            if (ModelState.IsValid)
            {
                db.sroAgents.Add(sroAgent);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(sroAgent);
        }

        // GET: sroAgents/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroAgent sroAgent = await db.sroAgents.FindAsync(id);
            if (sroAgent == null)
            {
                return HttpNotFound();
            }
            return View(sroAgent);
        }

        // POST: sroAgents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,UId,Name,FIO,Phone")] sroAgent sroAgent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sroAgent).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(sroAgent);
        }

        // GET: sroAgents/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroAgent sroAgent = await db.sroAgents.FindAsync(id);
            if (sroAgent == null)
            {
                return HttpNotFound();
            }
            return View(sroAgent);
        }

        // POST: sroAgents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            sroAgent sroAgent = await db.sroAgents.FindAsync(id);
            db.sroAgents.Remove(sroAgent);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sroSite/Controllers/sroTechSitesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sroSite.Models;

namespace sroSite.Controllers
{
    [Authorize]
    public class sroTechSitesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: sroTechSites
        public async Task<ActionResult> Index()
        {
            int page = 1;
            string search = Request["search"];
            int searchchanged = 0;

            IQueryable<sroTechSite> result = db.sroTechSites.Include(s => s.Agent).Include(s => s.Contact.Landlord).Include(s => s.Contact).Include(s => s.Negotiator);

            if (User.IsInRole("sroAgent"))
            {
                result = db.sroTechSites.Include(s => s.Agent).Include(s => s.Contact.Landlord).Include(s => s.Contact).Include(s => s.Negotiator).Where(s => s.Agent.UId == User.Identity.Name);
            }

            if (User.IsInRole("sroNegotiator"))
            {
                result = db.sroTechSites.Include(s => s.Agent).Include(s => s.Contact.Landlord).Include(s => s.Contact).Include(s => s.Negotiator).Where(s => s.Negotiator.UId == User.Identity.Name);
            }

            if (!String.IsNullOrEmpty(Request["page"]) && int.TryParse(Request["page"], out page))
            {

            }
            else
            {
                page = 1;
            }

            if (!String.IsNullOrEmpty(Request["searchchanged"]) && Request["searchchanged"] == "1")
            {
                page = 1;
            }

            if (!string.IsNullOrEmpty(search))
            {
                result = result.Where(x => x.Contact.Landlord.Name.Contains(search));
            }

            if (result != null)
            {
                ViewBag.TotalCount = result.Count();
            }
            else
            {
                ViewBag.TotalCount = 0;
            }

            result = result.OrderByDescending(x => x.Id).Skip(12 * (page - 1)).Take(12);

            var sites = result.ToList();

            List<int> dataCalls = new List<int>();
            List<int> dataCallsOpened = new List<int>();
            List<int> dataProposals = new List<int>();
            List<int> dataProposalsOpened = new List<int>();
            List<int> dataTasks = new List<int>();
            List<int> dataTasksOpened = new List<int>();
            foreach (var site in sites)
            {
                var tmpCalls = db.sroCalls.SelectMany(c => c.CallsTechSites).Where(x => x.TechSiteId == site.Id).Distinct().ToList();
                dataCalls.Add(tmpCalls != null ? tmpCalls.Count() : 0);
                var tmpOpenedCalls = tmpCalls.Where(x => x.Call.Status != "Завершен").ToList();
                dataCallsOpened.Add(tmpOpenedCalls != null ? tmpOpenedCalls.Count() : 0);
                var tmpProposals = db.sroProposals.Select(x => x.Call).SelectMany(c => c.CallsTechSites).Where(x => x.TechSiteId == site.Id).Distinct().ToList();
                dataProposals.Add(tmpProposals != null ? tmpProposals.Count() : 0);
                var tmpProposalsOpened = db.sroProposals.Where(p => p.Success == null).Select(x => x.Call).SelectMany(c => c.CallsTechSites).Where(x => x.TechSiteId == site.Id).Distinct().ToList();
                dataProposalsOpened.Add(tmpProposalsOpened != null ? tmpProposalsOpened.Count() : 0);
                var tmpTasks = db.sroTasks.Select(x => x.Call).SelectMany(c => c.CallsTechSites).Where(x => x.TechSiteId == site.Id).Distinct().ToList();
                dataTasks.Add(tmpTasks != null ? tmpTasks.Count() : 0);
                var tmpTasksOpened = db.sroTasks.Where(p => p.Success == null).Select(x => x.Call).SelectMany(c => c.CallsTechSites).Where(x => x.TechSiteId == site.Id).Distinct().ToList();
                dataTasksOpened.Add(tmpTasksOpened != null ? tmpTasksOpened.Count() : 0);
            }
            ViewBag.dataCalls = dataCalls;
            ViewBag.dataCallsOpened = dataCallsOpened;
            ViewBag.dataProposals = dataProposals;
            ViewBag.dataProposalsOpened = dataProposalsOpened;
            ViewBag.dataTasks = dataTasks;
            ViewBag.dataTasksOpened = dataTasksOpened;

            ViewBag.page = page;
            return View(await result.ToListAsync());
        }

        // GET: sroTechSites/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroTechSite sroTechSite = await db.sroTechSites.FindAsync(id);
            if (sroTechSite == null)
            {
                return HttpNotFound();
            }
            return View(sroTechSite);
        }

        // GET: sroTechSites/Create
        public ActionResult Create()
        {
            ViewBag.AgentId = new SelectList(db.sroAgents, "Id", "UId");
            ViewBag.ContactId = new SelectList(db.sroLandlordContacts, "Id", "Person");
            ViewBag.NegotiatorId = new SelectList(db.sroNegotiators, "Id", "UId");
            ViewBag.Landlords = new SelectList(db.sroLandlords, "Id", "Name");
            return View();
        }

        // POST: sroTechSites/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Pull,ERP,BSNum,Region,Filial,Address,Latitude,Longitude,ContractNumber,ContractDate,ContractExpire,AutoLong,AutoLongPeriod,SpecialContractTerms,PricePerMonth,PriceCompareToAvg,Tax,PaymentFrequency,Prepayment,LastChangeDate,LastChagePercent,aLowMarginSite,aDecreasedEquipment,aOftenGrowth,aLoyalClient,rImportantSite,rElectricityIsIncludedInRent,rBigAmountOfEqupment,rIncreasedAmountIfEquipment,rDiscountsOrLongPriceFreeze,rPaymentTrouble,rServiceTroubleOrOffset,Comment,Status,StatusDate,Result,SavingAmount,SavingRelative,SavingStartDate,SavingEndDate,EffectTotal,EffectYear,Effect17,Effect18,EffectRep,IsApproved,AgentId,NegotiatorId,ContactId")] sroTechSite sroTechSite)
        {
            if (ModelState.IsValid)
            {
                db.sroTechSites.Add(sroTechSite);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.AgentId = new SelectList(db.sroAgents, "Id", "UId", sroTechSite.AgentId);
            ViewBag.ContactId = new SelectList(db.sroLandlordContacts, "Id", "Person", sroTechSite.ContactId);
            ViewBag.NegotiatorId = new SelectList(db.sroNegotiators, "Id", "UId", sroTechSite.NegotiatorId);
            ViewBag.Landlords = new SelectList(db.sroLandlords, "Id", "Name");
            return View(sroTechSite);
        }

        // GET: sroTechSites/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sroTechSite sroTechSite = await db.sroTechSites.FindAsync(id);
            if (sroTechSite == null)
            {
                return HttpNotFound();
            }
            ViewBag.AgentId = new SelectList(db.sroAgents, "Id", "FIO", sroTechSite.AgentId);
            ViewBag.NegotiatorId = new SelectList(db.sroNegotiators, "Id", "FIO", sroTechSite.NegotiatorId);
            ViewBag.LandlordId = new SelectList(db.sroLandlords, "Id", "Name", sroTechSite.Contact.LandlordId);
            ViewBag.ContactId = new SelectList(db.sroLandlordContacts, "Id", "Person", sroTechSite.ContactId);

            return View(sroTechSite);
        }

        // POST: sroTechSites/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Pull,ERP,BSNum,Region,Filial,Address,Latitude,Longitude,ContractNumber,ContractDate,ContractExpire,AutoLong,AutoLongPeriod,SpecialContractTerms,PricePerMonth,PriceCompareToAvg,Tax,PaymentFrequency,Prepayment,LastChangeDate,LastChagePercent,aLowMarginSite,aDecreasedEquipment,aOftenGrowth,aLoyalClient,rImportantSite,rElectricityIsIncludedInRent,rBigAmountOfEqupment,rIncreasedAmountIfEquipment,rDiscountsOrLongPriceFreeze,rPaymentTrouble,rServiceTroubleOrOffset,Comment,Status,StatusDate,Result,SavingAmount,SavingRelative,SavingStartDate,SavingEndDate,EffectTotal,EffectYear,Effect17,Effect18,EffectRep,IsApproved,AgentId,NegotiatorId,ContactId")] sroTechSite sroTechSite)
        {
            if (true) //!User.IsInRole("sroManager")
            {
                sroTechSite currsite = db.sroTechSites.Where(x => x.Id == sroTechSite.Id).FirstOrDefault();
                if (currsite != null)
                {
                    currsite.Pull = sroTechSite.Pull;
                    currsite.AgentId = sroTechSite.AgentId;
                    currsite.NegotiatorId = sroTechSite.NegotiatorId;
                    currsite.ContactId = sroTechSite.ContactId;
                    currsite.Comment = sroTechSite.Comment;
                    currsite.Status = sroTechSite.Status;
                    currsite.StatusDate = DateTime.Now;

                    db.Entry(currsite).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }

            if (ModelState.IsValid)
            {
                db.Entry(sroTechSite).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");

sroSite/Views/sroTechSites/Delete.cshtml
@model sroSite.Models.sroTechSite

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>sroTechSite</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Agent.UId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agent.UId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact.Person)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact.Person)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Negotiator.UId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Negotiator.UId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pull)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pull)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ERP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ERP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BSNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BSNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Filial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContractNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContractNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContractDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContractDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContractExpire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContractExpire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AutoLong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AutoLong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AutoLongPeriod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AutoLongPeriod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialContractTerms)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialContractTerms)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PricePerMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PricePerMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceCompareToAvg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceCompareToAvg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentFrequency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentFrequency)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prepayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prepayment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastChangeDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastChangeDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastChagePercent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastChagePercent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aLowMarginSite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aLowMarginSite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aDecreasedEquipment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aDecreasedEquipment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aOftenGrowth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aOftenGrowth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.aLoyalClient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.aLoyalClient)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rImportantSite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rImportantSite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rElectricityIsIncludedInRent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rElectricityIsIncludedInRent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rBigAmountOfEqupment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rBigAmountOfEqupment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rIncreasedAmountIfEquipment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rIncreasedAmountIfEquipment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rDiscountsOrLongPriceFreeze)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rDiscountsOrLongPriceFreeze)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rPaymentTrouble)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rPaymentTrouble)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rServiceTroubleOrOffset)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rServiceTroubleOrOffset)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Result)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Result)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SavingAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SavingAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SavingRelative)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SavingRelative)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SavingStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SavingStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SavingEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SavingEndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Effect17)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Effect17)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Effect18)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Effect18)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EffectRep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EffectRep)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsApproved)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

sroSite/Views/sroTechSites/Index.cshtml
@model IEnumerable<sroSite.Models.sroTechSite>

@{
    ViewBag.Title = "Index";
}

<h2>
    Сайты
    @if (User.IsInRole("sroManager"))
    {        
        <a href="@Url.Action("Create", "sroTechSites")"><span class="glyphicon glyphicon-plus-sign"></span></a>
    }
</h2>

@{
    int page;
    string search;
}
@if (Request["page"].IsInt())
{
    if (int.TryParse(Request["page"], out page))
    {

    }
    else
    {
        page = 1;
    }
}
else
{
    page = 1;
}
@if (ViewBag.page > 0)
{
    page = ViewBag.page;
}
@if (!Request["search"].IsEmpty())
{
    search = Request["search"];
}
else
{
    search = string.Empty;
}

<form id="navData" name="navData">
    <div class="row">
        <div class="col-md-9">
            @if (ViewBag.TotalCount > 12)
            {
                <ul class="pagination" style="margin-top: 0px; margin-bottom: 5px;">
                    @for (int i = 0; i < ViewBag.TotalCount; i += 12)
                    {
                        <li class="@(page == ((i / 12) + 1) ? "active" : "")"><a href="@(Url.Action("Index", new { page = ((i / 12) + 1), search = search }))">@((i / 12) + 1)</a></li>
                    }
                </ul>
            }
        </div>
        <div class="col-md-3">
            <div class="input-group" style="margin-top: 0px; margin-bottom: 10px;">
                <!--<div class="form-group has-feedback has-clear">-->
                <input type="text" class="form-control" placeholder="Поиск" value="@(String.IsNullOrEmpty(search) ? "" : search)" onkeyup="searchKeyUp()" id="searchfield">
                <!--<span class="form-control-clear glyphicon glyphicon-remove form-control-feedback hidden" style="z-index: 10;pointer-events: auto;cursor: pointer;"></span>-->
                <!--</div>-->
                <div class="input-group-btn">
                    <button class="btn btn-default" style="height:34px;" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    @Html.Hidden("page", page)
    @Html.Hidden("search", search)
    @Html.Hidden("searchchanged")
</form>

<table class="table">
    <tr>
        <th></th>
        <th>
            Статус
        </th>
        <th>
            ERP
        </th>
        <th>
            Контрагент
        </th>
        <th>
            Контакт
        </th>
@if (User.IsInRole("sroManager") || User.IsInRole("sroNegotiator"))
{
        <th>
            Агент
        </th>
}
@if (User.IsInRole("sroManager") || User.IsInRole("sroAgent"))
{
        <th>
            Сопровожд.
        </th>
}
        <th>Звонки</th>
        <th>Предл.</th>
        <th>Задачи</th>
        <th style="width: 90px;"></th>
    </tr>
@{ 
    int ind = 0;
    List<int> dataCalls = ViewBag.dataCalls;
    List<int> dataCallsOpened = ViewBag.dataCallsOpened;
    List<int> dataProposals = ViewBag.dataProposals;
    List<int> dataProposalsOpened = ViewBag.dataProposalsOpened;
    List<int> dataTasks = ViewBag.dataTasks;
    List<int> dataTasksOpened = ViewBag.dataTasksOpened;
}

@foreach (var item in Model) {
    <tr  style="font-size: small;">
        <td>
            @if (User.IsInRole("sroManager") || User.IsInRole("sroAgent")) {
                <a href="@Url.Action("Create", "sroCalls", new { siteId = item.Id })"><span class="glyphicon glyphicon-earphone"></span></a>
            }            
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td> 
        <td >
            @Html.DisplayFor(modelItem => item.ERP)
        </td> 
        <td>
            @Html.ActionLink(item.Contact.Landlord.Name, "Details", "sroLandlords", new { id = item.Contact.LandlordId }, null)
        </td>
        <td>
            @Html.ActionLink(item.Contact.Person, "Details", "sroLandlordContacts", new { id = item.ContactId }, null)
        </td>

        @if (User.IsInRole("sroManager") || User.IsInRole("sroNegotiator"))
        {
            <td>
                @Html.ActionLink(item.Agent.Name, "Details", "sroAgents", new { id = item.AgentId }, null)
            </td>
        }
        @if (User.IsInRole("sroManager") || User.IsInRole("sroAgent"))
        {
            <td>
                @Html.ActionLink(item.Negotiator.FIO.Split(' ')[0], "Details", "sroNegotiators", new { id = item.NegotiatorId }, null)
            </td>
        }
        <td>@dataCallsOpened[ind] из @dataCalls[ind]</td>
        <td>@dataProposalsOpened[ind] из @dataProposals[ind]</td>
        <td>@dataTasksOpened[ind] из @dataTasks[ind]</td>
        <td style="vertical-align: middle; text-align: center; min-width: 90px;">

            <a href="@Url.Action("Edit", "sroTechSites", new { id = item.Id })"><span class="glyphicon glyphicon-pencil"></span></a>

            <a href="@Url.Action("Details", "sroTechSites", new { id = item.Id })"><span class="glyphicon glyphicon-list-alt"></span></a>
            @if (User.IsInRole("sroManager"))
            {
                <a href="@Url.Action("Delete", "sroTechSites", new { id = item.Id })"><span class="glyphicon glyphicon-trash"></span></a>
            }
        </td>
    </tr>
    ind++;
}

</table>
@section Scripts {
    <script>
        function searchKeyUp() {
            document.getElementById("search").value = document.getElementById("searchfield").value;
            document.getElementById("searchchanged").value = 1;
        }

        $('.has-clear input[type="text"]').on('input propertychange', function () {
            var $this = $(this);
            var visible = Boolean($this.val());
            $this.siblings('.form-control-clear').toggleClass('hidden', !visible);
        }).trigger('propertychange');

        $('.form-control-clear').click(function () {
            $(this).siblings('input[type="text"]').val('')
                .trigger('propertychange').focus();
        });
    </script>
}